include: 'https://gitlab.gnome.org/GNOME/citemplates/raw/master/flatpak/flatpak_ci_initiative.yml'

variables:
    BUNDLE: "org.gnome.Lollypop-next.flatpak"
    GIT_SUBMODULE_STRATEGY: recursive

flatpak:
    variables:
        MANIFEST_PATH: "org.gnome.Lollypop.json"
        FLATPAK_MODULE: "lollypop"
        RUNTIME_REPO: "https://flathub.org/repo/flathub.flatpakrepo"
        APP_ID: "org.gnome.Lollypop"
    extends: .flatpak
